### ISSUE TITLE
Can not add features to uploaded shapefile

### ISSUE THREAD

**Issue by assia-benseddik** [OneOffTech/geoserver-client-php#30] opened 2022-08-25 12:50 UTC
Hello,
I'm working on a web site where you can import a zipped shapefile on your device to geoserver and gives the possibility to display it, add features to that shapefile, modify it, or delete it using openlayers, php and ajax.
At first i imported the shapefile myself to Geoserver and did my web site and everything was workin great. But when i added the import part using geoserver-client-php, the shapefile gets added to geoserver plus i can modify it or delete by wfs requests but adding features doesn't get saved in geoserver at all when it's the same code.
I'm really stuck on this for more than 2 weeks, could anyone help me?

**Comment by avvertix** [comment] 2022-08-25 18:16
Duplicate of #32

**Closed as not planned by avvertix** 2022-08-25 18:16 UTC
